### ISSUE TITLE
How is the progress of opensource?

### ISSUE THREAD

**Issue by chenwei-tw** [IBM/microprobe#1]
May I ask how is the progress of opensource?

I think there are many guys like me, who look forward to seeing it. :+1:

**Comment by rbertran** [comment]
@chenwei-tw Thanks for your interest. Due to higher priority internal deadlines I could not spend time on this task. 

Progress-wise we are almost ready to opensource the framework and if time permits, I'd like to finish this item within the next month.  

We'll keep you posted in that regard,

Thanks,

**Comment by rbertran** [comment]
Microprobe released. Sorry for the delay :P

- Source code repo: https://github.com/IBM/microprobe
- Documentation: https://ibm.github.io/microprobe/
- Installation packages: https://pypi.org/search/?q=Microprobe
