### ISSUE TITLE
Adding new features memory access pattern - Randomness + Temporal locality

### ISSUE THREAD

**Issue by rgokulsm** [IBM/microprobe#13]
Hello @rbertran,

Is there some existing way for me to get randomized memory access patterns? (may it could take only the memory footprint as parameter). 

Best case scenario would be if a stream in the GenericMemoryStreamsPass could be random access, similar to:

```
GenericMemoryStreamsPass([[0, 4 * 1024 * 1024, 10, 128, 1], [1, 256, 5, 64, 1]])
```
And the random pattern could also be used with some probability, similar to the 10:5 ratio above.

As we discussed at some point, this might provide some more control for cache miss rates etc.

Thanks!!

**Comment by rgokulsm** [comment]
Hello @rbertran,

I tried the update and I do see variability in cache miss rates according to the knob, but I'm not 100% sure if its working as expected. 

Here is a snippet of the generate instructions:

```ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000007400) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000007400) */
ADDI x5, x5, 0x182 /* Added to compute address: Address((char) stream1[4194304]+0x0000000000007400) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000006280) */
ADDI x5, x5, 0x681 /* Added to compute address: Address((char) stream1[4194304]+0x0000000000006280) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000005400) */
ADDI x5, x5, 0x281 /* Added to compute address: Address((char) stream1[4194304]+0x0000000000005400) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000004980) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000004980) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000004980) */
ADDI x5, x5, 0x83 /* Added to compute address: Address((char) stream1[4194304]+0x0000000000004980) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000003100) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000003100) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000003100) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x0000000000003100) */
ADDI x5, x5, 0x384 /* Added to compute address: Address((char) stream1[4194304]+0x0000000000003100) */
ADD x17, x16, x15
LW x18, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000003100) */
ADD x10, x19, x9
ADD x23, x13, x21
MUL x28, x27, x26
SW x29, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000004980) */
SW x17, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000005400) */
SW x18, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000006280) */
ADD x22, x20, x10
MUL x0, x30, x23
MUL x25, x24, x28
MUL x12, x11, x8
SW x14, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000007400) */
LW x15, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000006300) */
LW x16, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000002480) */
SW x0, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000006100) */
LW x9, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000004780) */
ADD x21, x19, x12
LW x13, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000003b00) */
MUL x27, x26, x15
ADD x17, x29, x16
SW x18, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000000600) */
MUL x20, x10, x9
MUL x23, x22, x21
LW x30, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000005380) */
MUL x24, x28, x27
LW x25, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000007580) */
SW x8, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000000680) */
ADD x14, x11, x20
ADD x12, x0, x23
SW x30, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000001180) */
MUL x13, x19, x24
ADD x26, x15, x25
LW x16, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x0000000000002980) */


```

There are a stream of updates to x5, followed by many loads and stores which simply use "0x0(x5)", which I am guessing is not right?

I think this might be inadvertently enabling better temporal locality by using continuous  "0x0(x5)".

But that also brings me to a different question. Is it possible to have an additional feature to loop back and reuse some recent addresses. The current pass is basically a streaming pass (without the randomness) - achieving spatial locality based on the stride. But doesn't have any temporal locality unless the stride is small enough to fit within the same cache block. 

So it would be useful to have some feature to tunably reuse some recent history.

**Comment by rbertran** [comment]
Definitely, something seems wrong. Can you provide the pass configuration you are using?

**Comment by rgokulsm** [comment]
```
passes = [
                    structure.SimpleBuildingBlockPass(self.args.loop_size),
                    initialization.ReserveRegistersPass(reserved_registers), #new
                    instruction.SetInstructionTypeByProfilePass(thisdict),
                    initialization.InitializeRegistersPass(),
                    initialization.InitializeRegistersPass(v_value=(1.000000000000001, 64)),
                    initialization.InitializeRegisterPass("X1",1), #new - global pattern option #1 (other option is X0)
                    initialization.InitializeRegisterPass("X2", int(local_pattern, 2)),#entire local pattern is held here
                    initialization.InitializeRegisterPass("X3", 0),#loop count
                    initialization.AddInitializationAssemblyPass("andi x4, x2, 1"), #x4 starts with lowermost bit of x2
                    instruction.SetInstructionOperandsByOpcodePass(branch_instrs, 1, self.target.isa.registers["X4"]), #new - Operand 1 of all branches will bw x4 - this is local
                    instruction.SetInstructionOperandsByOpcodePass(branch_instrs, 2, global_pattern_regs), #new - Operand 2 of all branches will be X0/X1 - this is global
                    branch.BranchNextPass(),
                    branch.FixIndirectBranchPass(),
                    initialization.AddFinalizationAssemblyPass(
                        "addi x3, x3, 1 \n" +  # Updating loop count
                        # Compare and reset based on pattern length
                        "slti x4, x3, %d\n" % min(64, len(local_pattern)) + #x4 is used as a temp variable here
                        "bne x4, x0, 8 \n" +  #
                        "addi x3, x0, 0 \n" +  # Reset to zero
                        "addi x0, x0, 0"  # nop
                    ),
                    initialization.AddFinalizationAssemblyPass(
                        "srl x4, x2, x3\n"+
                        "andi x4, x4, 1"
                        ), #put new value into x4
                    address.UpdateInstructionAddressesPass(),
                    memory.GenericMemoryStreamsPass([[1, 4*1024*1024, 1, 128, 1,32*1024]]),
                    register.DefaultRegisterAllocationPass(dd=6),
                    address.UpdateInstructionAddressesPass(),

                ]


```

**Comment by rgokulsm** [comment]
Adding to the above, I noted a similar issue with the '-1' parameter also i.e. total random.

**Comment by rbertran** [comment]
Found the bug, it will be fixed in the next update. 

Regarding randomness and temporal locality, Here are some thoughts: 

The stream pass, by definition is a case of high spatial locality. References to an array is done in consecutive manner, so the probability to access data nearby current access is quite high. One can control the spatial locality by using the stride parameters and the new random parameter. Using that, one can trick the pre-fetchers and reduce significantly the spatial locality. 

Regarding temporal locality, we don't have specific knob to play with it directly... in the past that was somehow handled by using multiple streams with different accesses size/access patterns. I.e. if one defines a small stream, that implicitly will have high spatial locality but also high temporal locality since accesses to the same location will be generated often. Then, with the right balance between a different streams, one can control the overall temporal locality of memory accesses. That said, I think it'd be good to have some sort of temporal locality parameter for each stream to provide full control.

I'm thinking in the following: an extra parameter (X,Y): which is a tuple with two integers specifying that the last X accesses are going to accessed again Y times before moving forward to the next addresses.  Examples:

- base access pattern : 0 1 2 3 4 5 6 7 8 9 0 1 2 ...
- base + (2, 1): 0 1 0 1 2 3 2 3 4 5 4 5 6 7 6 7 8 9 8 9 0 1 0 1...
- base + (3, 2): 0 1 2 0 1 2 0 1 2 3 4 5 3 4 5 3 4 5 6 7 8 6 7 8 6 7 8 9 0 1 9 0 1 9 0 1
 
Let me know any suggestions,

**Comment by rgokulsm** [comment]
Hello @rbertran,

Yup, I guess using a stream with a small footprint an having it looping over would help improve temporal locality. If there's any difficulty in implementing the knob you've mentioned, then I can try this out.

But otherwise i think what you have suggested above looks great - I think this would be a really good way to control the per-stream temporal locality easily with knobs.

**Comment by rbertran** [comment]
Repository and distribution updated. I've extended the memory stream pass definition based on my previous comment, with extra parameters to control the repetition of the of the memory access to have another level of control of the temporal locality.

**Comment by rgokulsm** [comment]
Thanks Ramon. I am using (1,0) as the default value for the temporal parameter -  I assume this should imply no temporal reuse.

 I am trying out the randomness aspect at the moment. I tried using the (-1) flag i.e. total randomness, and I see that almost 99% of the instructions are:

```
ADDI x5, x5, -0x7ff
```

A snippet is below:
```
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
ADDI x5, x5, 0x3b6 /* Added to compute address: Address((char) stream1[4194304]+0x00000000000db200) */
MUL x8, x7, x0
LW x9, 0x0(x5) /* Address: Address((char) stream1[4194304]+0x000000000025c280) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
ADDI x5, x5, 0x7ff /* Added to compute address: Address((char) stream1[4194304]+0x000000000034ba80) */
```

Is this expected?

**Comment by rbertran** [comment]
Yes, that behavior is expected. When generating a particular memory access pattern, we need to add any necessary instructions to compute next address. 
- If the next address nearby the previous access, just using the immediate operand is enough or with just one instruction is enough (this was the most used use-case)
- If the next address is far, then we need many instructions to update the register. 

In the example, you are generating a complete random pattern, and therefore we need many add instructions to update the base register. For now, you can limit that by setting the random parameter from -1 (total random) to e.g. 0x800 to limit the maximum distance between accesses and therefore the extra ADDI instructions. 

That said, one optimization we do in other back-ends, which I've not yet enabled in RISCV,  is to reload the entire address from scratch (which takes only 2-3 instructions) whenever we need to add more ADDI instructions. I'll implement that on next udpate.

**Comment by rgokulsm** [comment]
Sounds good Ramon, thanks! The randomization is working smoothly otherwise. Will test the temporal locality and update.

**Comment by rgokulsm** [comment]
I tested the temporal locality. It works perfectly with 1 difference from what you wrote earlier.

'Y' indicates total # times accessed (not re-access). i.e. Y=1 indicates no temporal locality, Y=2 indicates 1 time repeat.

```
base access pattern : 0 1 2 3 4 5 6 7 8 9 0 1 2 ...
base + (2, 2): 0 1 0 1 2 3 2 3 4 5 4 5 6 7 6 7 8 9 8 9 0 1 0 1...
```

This is perfectly fine I guess, but just clarifying the difference from your earlier example. Thanks!

I'll keep this issue open for the earlier optimization you mentioned.

**Comment by rbertran** [comment]
- Fixed the implementation to match the documentation and the original description, 'Y' is the number or 're-accesses' . 
- Implemented the code generation overhead optimization. To compute an address two options are evaluated:
    1. computing displacement via ADDI instructions from previous address
    2. using relocations to let the linker compute the address to the target symbol+displacement.

  The one with less instructions is selected.

**Comment by rbertran** [comment]
Repo and wheel packages updated. Try it out and let's see still have some issue pending.

**Comment by rgokulsm** [comment]
Checked both and they seem to work well. 

I verified that for the '-1' (total randomization) scenario, the ADDI instructions do not show up - seems to work as expected.

In summary I am able to use the temporal locality as well as the randomization features. Thanks! Closing the issue.

**Comment by rgokulsm** [comment]
Hi @rbertran,

Reopening this issue for a clarification about memory locality:

Does X*(Y+1) have to be less than the number of memory instructions per loop iteration?

For example say I want to have 100 memory operations repeat 10 times. But say I have only 20 memory ops in an iteration. So would this temporal locality be achieved over 50 iterations?

**Comment by rbertran** [comment]
In short yes, but with some limitations if we don't have enough memory accesses in a loop iteration.  
The way the memory stream pass is implemented is as following:
- The pattern is generated for the particular loop statically, e.g. if there are 10 mem accesses, they access the 10 positions defined in the memory stream. This is static code, so next iterations can only modify the memory accesses if we modify the base address registers of the memory operation on each iteration (effectively adding some displacement on the pattern already generated) 
- At the and of each iteration, we look at the maximum address accessed by the stream, and divide that by the stream size to know how much we can modify the base pointer. If possible we advance the base pointer for the following iteration. We also check the iteration count and reset to the initial value after N iterations, to avoid out of bounds accesses. 

In an example. Let's assume we want to generate the pattern: 1,1,2,2,3,3,4,4,5,5, (5 is the maximum size of the array):

- If we have 4 memory operations in a loop, the pattern generated will be (some cropping):
   - 1,1,2,2 (first iteration)
   - 3,3,4,4 (second iteration, at the end of the iteration the pointer will be reset because if advanced will go out of bounds)
   - 1,1,2,2 ...
- If we have 5 memory operations in a loop (more cropping):
   - 1,1,2,2,3 (first iteration, and reset)
   - 1,1,2,2,3
- If we have 1 memory operation in a loop (no pattern control):
   - 1 (first iteration)
   - 2 
   - 3
   - 4
   - 5
   - 1 (sixth iteration)
- If we have 35 memory operations in a loop (pattern generated 3 times with small cropping at the end):
   - 1,1,2,2,3,3,4,4,5,5,1,1,2,2,3,3,4,4,5,5,1,1,2,2,3,3,4,4,5,5,1,1,2,2,3 (first iteration and reset)
   - 1,1,2,2,3,3,4,4,5,5,1,1,2,2,3,3,4,4,5,5,1,1,2,2,3,3,4,4,5,5,1,1,2,2,3,

When using -1 (total random), there will be a high probability that an address close to the maximum stream address is accessed on the first iteration. That will lead the pointers to be reset on each iteration, effectively, repeating the same pattern on each iteration. If you use a random value of >N, you are limiting the maximum value that can be reached and therefore creating a different memory accesses on different iteration. 

Example: memory stream size 2000, 10 memory accesses per iteration:

- if -1 is specified:
  - 23,1999,500,234,12,950,456,912,1245,1577 (1st iteration  & reset)
  - 23,1999,500,234,12,950,456,912,1245,1577 (2st iteration)
- if 250 (randomness in chunks of 250) is specified:
  - 12,244,135,33,77,266,456,332,499,270 (1st iteration)
  - 512,744,635,533,577,766,956,832,999,770 (2nd iteration -- same pattern +500)
  - 1012,1244,1135,1033,1077,1266,1456,1332,1499,1270 (3rd iteration -- same pattern +1000)
  - 1512,1744,1635,1533,1577,1766,1956,1832,1999,1770 (4th iteration -- same pattern +1500)
  - 12,244,135,33,77,266,456,332,499,270 (5th iteration - reset)

So, the more accesses (the bigger the loop size) the better since the loop will be able to replicate many times the requested access pattern (with maybe some cropping at the end, when resetting).  In particular, for random patterns, if you want to generate misses, I'd specify very big streams sizes but limit randomness so that keep advancing on the random pattern many time (> the cache set associativity) so that eventually when we reset the pointer, the lines have been cast out.  

We also have a memory pass, which given a cache hierarchy definition , it generates the right memory pattern to generate the specific activity in each cache level. Eg. 10% access to L1, 40 accesses to L2 and 50% accesses to L3. It was tested and validated on POWER, not on RISCV, we can try to look at it, if the generic memory stream pass does not help you get what you need.

**Comment by rgokulsm** [comment]
Thanks! I don't think this should be much of a problem. My takeaway from the above (from the temporal locality perspective) is that if X and Y are low (compared to the number of memory accesses in the loop iteration), there is a higher guarantee of the temporal locality matching the exact requirements.

And I guess there is a similar analogy for the random access.

As of now I believe that using small values for the above, along with employing right memory footprints/strides and more than 1 memory stream, should be able to achieve a pretty wide range of cache miss rates. 

So we should be fine at the moment - I will open a separate issue if we need to try the cache hierarchy based memory pass. Thanks!
