### ISSUE TITLE
[RiscV] Microbenchmark generated through mpt2c crashes (segfault)

### ISSUE THREAD

**Issue by TheArni** [IBM/microprobe#15]
Using the [attached mpt file](https://github.com/IBM/microprobe/files/4895465/vecsum.0.mpt.zip) (generated via chopstix), I correctly created a microbenchmark using the `mpt2c` tool. However there seems to be some sort of issue regarding the fixing of memory addresses. The .c source code is the same which microprobe generates given the scenario above ([benchmark.c](https://github.com/IBM/microprobe/files/4926093/benchmark.txt)). The crash (segfault) happens at the last of the following lines (the `SD` instruction at line 378):

```
367 __asm__(" MEMACCESS_FIX_0_pcrel_1:AUIPC x2, %pcrel_hi(MEMACCESS_FIX_0) ");      
368 __asm__(" ADDI x2, x2, %pcrel_lo(MEMACCESS_FIX_0_pcrel_1) ");                   
369 __asm__(" MEMACCESS_FIX_1_pcrel_2:AUIPC x8, %pcrel_hi(MEMACCESS_FIX_1) ");      
370 __asm__(" ADDI x8, x8, %pcrel_lo(MEMACCESS_FIX_1_pcrel_2) ");                   
371 __asm__(" MEMACCESS_FIX_2_pcrel_3:AUIPC x15, %pcrel_hi(MEMACCESS_FIX_2) ");     
372 __asm__(" ADDI x15, x15, %pcrel_lo(MEMACCESS_FIX_2_pcrel_3) ");                 
373 __asm__(" ADDI x3, x0, 0x0 ");                                                  
374 __asm__(" first:ADDI x0, x2, -0x40 ");                                          
375 __asm__(" ADDI x1, x2, -0x40 ");                                                
376 __asm__(" ADDI x10, x2, -0x40 ");                                               
377 __asm__(" ADDI x11, x2, -0x40 ");                                               
378 __asm__(" SD x8, 0x38(x2) "); 
```
When debugging the execution, one would expect that the `x2` register would point to a region of memory within MEMACCESS_FIX_0 (as is set above in the code), however this is not the case (you can check this by reading the value of `x2` and comparing it to the position of MEMACCES_FIX_0 symbol which can be found by using the `nm` utility). This suggests that maybe the instructions being generated for memory fixing is not right? I'm not sure.

Aside from this, I also noticed some weird code involving writing to the `x0` register, or using "protected" registers such as the stack pointer (which is, precisely, `x2`), etc. I'm not sure if that's intended behavior or not.

If you need any additional information, files, whatever else to solve this issue, please don't hesitate to ask me.

**Comment by rbertran** [comment]
Hi @TheArni,

For some reason, I'm unable to reproduce the problem. Using the latest version of microprobe, I did the following steps:

1. Uncompress the zip provided
2. Edit the mpt file to not use the state file (otherwise next step fails)
3. executed: `mp_mpt2c.py -T riscv_v22-riscv_generic-riscv64_linux_gcc --fix-indirect-branches --fix-branch-next --fix-memory-registers -O /tmp/test.c -t ./vecsum.0.mpt --endless` to generate and endless loop from the mpt definition
4. checked the code generated: is the same, except that there is a `__asm__(".balign 64");` statement before the endless loop (`first` label)
5. compiled the generated `/tmp/test.c` file using : `riscv64-linux-gnu-gcc -static /tmp/test.c -o /tmp/test`
6. executed the `/tmp/test` binary using qemu as following: `qemu-riscv64 /tmp/test` and it worked as expected (no error, no segfault)

I tried with and without the `--endless` flag and code worked. Let's check all the details to make sure I can reproduce the error. Check the steps I provided to see what is different.  AFAIK, things that may differ from you environment:

- state file. Please provide it and I'll check again.
- exec environment: I run 64 bits risc-v on qemu, are you using 64 bits? you are on real machine right? Can you try if in qemu the code fails too?

**Comment by TheArni** [comment]
Sorry, I thought the zip included the state file. My bad. [Here it is](https://github.com/IBM/microprobe/files/4946077/vecsum.0.mps.zip).

Indeed, we are running a real 64-bit Risc-V machine. I will also investigate running without the state file, as well as using qemu as you suggested.

**Comment by TheArni** [comment]
I can confirm that, on a real machine, the benchmark runs fine when the state file is deleted. Does this suggest maybe that the gathered state data is wrong?

**Comment by rbertran** [comment]
I tried with and without the state file, and the benchmark runs in both cases. I've even compiled the `benchmark.txt` provided in the first msg that generate the seg. fault in your env, and if works in my environment. 

Can you generate also the execution trace of execution? E.g. in GDB on real machine, do step by step and dump the instruction trace as well as the register contents.

**Comment by TheArni** [comment]
I wanted to record an execution using gdb, however that is not possible with RiscV. I am unsure about how to send you the instruction trace. If you meant the backtrace, it just has the "main" function. The following is the register dump at the moment of the crash, I hope it is enough:

```
ra             0x12b08	0x12b08
sp             0x12b48	0x12b48
gp             0x0	0x0
tp             0x15564c3720	0x15564c3720
t0             0xfff1	65521
t1             0x1041c	66588
t2             0x155630f000	91640360960
fp             0x12be8	0x12be8
s1             0x0	0
a0             0x12b08	76552
a1             0x12b08	76552
a2             0x3fffd73088	274875232392
a3             0x0	0
a4             0x3fffd72f18	274875232024
a5             0x12c98	76952
a6             0x0	0
a7             0x15564328a8	91641555112
s2             0x3fffaf9228	274872635944
s3             0x0	0
s4             0x1	1
s5             0x1555571888	91626084488
s6             0x5e000	385024
s7             0x0	0
s8             0x5e000	385024
s9             0x2aaaba67d4	183252969428
s10            0x5e000	385024
s11            0x2aaad3e920	183254640928
t3             0x1556332152	91640504658
t4             0x15563ea690	91641259664
t5             0x0	0
t6             0x563ea690	1446946448
pc             0x10e4a	0x10e4a <main+1132>
```

**Comment by rbertran** [comment]
On the GDB support, according to the documentation GDB supports RISCV since version 8.3 . Not sure which problem are you facing. Which version are you using? You might want to install the latest version available and retry. If that does solve the issue, feel free to share more details to see if we can solve the issue. GDB support is a must for the type of work you are pursuing ;)  

On the particular crash, I understand that the crash happens at the following statement: `__asm__(" SD x8, 0x38(x2) ");` and 
at that point the register `x2`, which is the `sp`, has a value of 0x12b48 . The address generated in the instruction is: `0x12b80`  (the `x2` value + `0x38`). From the code, the `MEMACCESS_FIX_0` is 160 bytes array, and `0x12b48` should be the base address, so  `0x12b48+0x38` is within the array. However, we need to check if `0x12b48` is actually the base address of the array when loaded into the memory,  Can you check that? You can do so in GDB (you can add a breakpoint and dump symbol information [1]). Alternatively, you might want to check also a RISCV simulation env so that you can develop/test on you laptop and double check issues between the environments [2].

[1] https://ftp.gnu.org/old-gnu/Manuals/gdb/html_chapter/gdb_12.html
[2] https://github.com/riscv/riscv-isa-sim

**Comment by TheArni** [comment]
Indeed GDB does work on my environment, however in my previous comment I meant that specifically the record feature (which lets you record an execution for later playback) isn't supported.

Anyway, gdb reports that `MEMACCESS_FIX_0` begins at address `0x21070`:

```
Program received signal SIGSEGV, Segmentation fault.
main (argc=0, argv=0x0, envp=0x0) at benchmark.c:378
378	__asm__(" SD x8, 0x38(x2) ");
(gdb) info address MEMACCESS_FIX_0
Symbol "MEMACCESS_FIX_0" is static storage at address 0x21070.
```

On the background, I am also working on setting up a working risc-v environment (currently with qemu, although i will take a look at the link you have provided. I currently do not have an ETA for that.

**Comment by TheArni** [comment]
I think I might have found the issue. By inspecting the compiled code using `objdump -d -S benchmark`, I have found the following:

```
__asm__(" MEMACCESS_FIX_0_pcrel_1:AUIPC x2, %pcrel_hi(MEMACCESS_FIX_0) ");
__asm__(" ADDI x2, x2, %pcrel_lo(MEMACCESS_FIX_0_pcrel_1) ");
   10e20:       34818113                addi    sp,gp,840 # 13348 <__FRAME_END__+0x1104>
```
It looks like the compiler is changing the meaning of the written inline assembly. It is probably trying to do some optimization (even though I am compiling with `-O0`) using the `gp` register. The compiler probably doesn't realize that this register is modified earlier by the code that sets the initial state of the registers from the microbenchmark's state file, which explains why it wasn't crashing when I removed the state file.

I am unsure on how to proceed, but I guess this issue could be closed given that it is not microprobe's fault per se. However, I'd like to know what version of gcc you are using (I am using 10.1.1) so I can look further into it.

**Comment by rbertran** [comment]
Very interesting find out. My toolchain (which is much older GCC 7.5 / 7.1) was not that smart and left the code untouched. I think that there is workaround to this problem. We can modify microprobe to generate `__asm__ __volatile__` statements, instead of only `__asm__`. This should force the compile to generate the code `as is`. Can you give a try and let me know if that solves the issue? If so, I'll work in the fix and meanwhile you'll have a workaround to the issue. 

Lesson for next time: I should have requested the objdump, which is what really get executed, and we'd have detected the issue earlier. 

Regarding the GDB, I was not referring to the _record/replay_ capabilities. I was thinking in starting gdb, set a breakpoint to the region of interest, and from that point on: advance one instruction at a time, dump the instruction and the registers, until we get the failure. This can be specified using GDB command file (no need to do it manually ;) ).

**Comment by TheArni** [comment]
I modified microprobe to generate a microbenchmark using the suggested statements, but the binary is still getting generated with the same problems. I am investigating to see if there are other compiler parameters I could use.

**Comment by rbertran** [comment]
I always though that the compiler does not touch inline asm statements, specially the volatile ones. Can you try to generate the intermediate files? Instead of compiling , just generate the assembly (e.g. `gcc -Wa,-adhln -g test.c > test.s`) and check if the assembly statements are being modified during `gcc` compilation.  If not, then it is the assembler (`as`) that is being fancy and modifies the code.

**Comment by rbertran** [comment]
I compiled a new toolchain and reproduced the problem. It turns out that is neither the  gcc or the assembler.  The issue comes from link time optimization. The linker [relaxation](https://www.sifive.com/blog/all-aboard-part-3-linker-relaxation-in-riscv-toolchain) is messing up the assembly code.  To avoid that use the following flag: `-mno-relax` which passes the information to the linker to not apply any link time optimization.

**Comment by TheArni** [comment]
Very nice find!

I can confirm it works on my end by compiling with that option. The issue can probably be closed now. Thanks.

**Comment by rbertran** [comment]
I'll keep this until we document the findings. Todo:

 - [ ] Update mp_mpct2c tool documentation to warn users about this behavior
