### ISSUE TITLE
[RISCV] NotImplementedError when using mpt2c with branch fixing

### ISSUE THREAD

**Issue by TheArni** [IBM/microprobe#21]
When trying to use the mpt2c tool to generate a C source file from an MPT file (generated using chopstix) a NotImplementedError exception is thrown, corresponding to the line 838 of `src/microprobe/passes/branch/__init__.py`

The MPT file in question is [this one](https://github.com/IBM/microprobe/files/5163217/mpt.zip). The command to generate the C source file is as follows: `mp_mpt2c.py -T riscv_v22-riscv_generic-riscv64_linux_gcc --fix-indirect-branches --fix-branch-next --fix-memory-registers --endless -t bt.mpt -O /tmp/temp.c`

The last instruction in the BBL is `JALR (JALR_V0) Description: Jump and Link Register: Jump to rs1 plus the 12-bit signed immediate while saving PC+4 into rd`.

**Comment by rbertran** [comment]
Problem detected and solved: the implementation of the corner case where the last instruction is a branch without a target set was missing. For now, if that's the case the instruction is converted to a _nop_ since branch to next does not make sense (no next instructions) and branch to the first instruction creates an endless loop without the user expecting it. 

Fixes will be released in the following repo update.
